# Generated by Django 3.2.15 on 2022-12-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_order_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="host",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
