# Generated by Django 3.2.15 on 2022-12-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_order_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="day_to_build",
            field=models.IntegerField(default=0),
        ),
    ]
