# Generated by Django 3.2.15 on 2022-12-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_order_day_to_build"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("lp", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Jan", max_length=20)),
                ("surname", models.CharField(default="Nowak", max_length=20)),
                ("utility_1", models.CharField(default="-", max_length=1)),
                ("utility_2", models.CharField(default="-", max_length=1)),
                ("utility_3", models.CharField(default="-", max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="dryer_model",
            field=models.CharField(default="dryer_20_t", max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="orderer_name",
            field=models.CharField(default="Jan", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="orderer_surname",
            field=models.CharField(default="Nowak", max_length=20),
        ),
    ]
