# Generated by Django 3.2.15 on 2022-12-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20221211_1808"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="dryer_model",
            field=models.CharField(default="dryer_20_t", max_length=11),
        ),
        migrations.AlterField(
            model_name="worker",
            name="utility_3",
            field=models.CharField(default="U", max_length=1),
        ),
    ]
