# Generated by Django 3.2.15 on 2022-12-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221212_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
    ]
